-- USER TABLE
CREATE TABLE "user" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    profile VARCHAR(120),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- BLOG TABLE
CREATE TABLE blog (
    id SERIAL PRIMARY KEY,
    title VARCHAR(90) NOT NULL,
    description TEXT NOT NULL,
    image VARCHAR(100),
    slug TEXT UNIQUE,
    author_id INT REFERENCES user(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



